# Common
whisper-mq.broker-host=127.0.0.1
whisper-mq.broker-port=9999

# Broker ??

whisper-mq.flush-threshold=100
whisper-mq.max-file-size=10485760
whisper-mq.flush-interval-millis=10000
whisper-mq.get-flush-timeout-millis=5000
whisper-mq.window-size-millis=10000
whisper-mq.max-dead-letter-retry-count=8

# Consumer
WhisperMQ.consumer-timeout=5000

# Producer
whisper-mq.producer-timeout=4000
whisper-mq.producer-retryCountLimit=3
whisper-mq.producer-retryTimeCoefficient=500