# Broker ??
whisper-mq.broker-port=9999
whisper-mq.flush-threshold=100
whisper-mq.max-file-size=10485760
whisper-mq.flush-interval-millis=10000
whisper-mq.get-flush-timeout-millis=5000
whisper-mq.window-size-millis=10000
whisper-mq.max-dead-letter-retry-count=8